"""Initial 16 tables

Revision ID: 7ff6c40adca2
Revises: None
Create Date: 2026-08-31 23:41:34.938207

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ff6c40adca2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('previous_state', sa.String(length=50), nullable=True),
    sa.Column('new_state', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_case_id'), 'audit_logs', ['case_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=False),
    sa.Column('customer_segment', sa.String(length=100), nullable=True),
    sa.Column('lifetime_value', sa.Float(), nullable=True),
    sa.Column('successful_payment_count', sa.Integer(), nullable=True),
    sa.Column('failed_payment_count', sa.Integer(), nullable=True),
    sa.Column('opt_out', sa.Boolean(), nullable=True),
    sa.Column('communication_consent', sa.Boolean(), nullable=True),
    sa.Column('preferred_channel', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.String(length=50), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.create_table('merchant_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('minimum_retry_interval', sa.Integer(), nullable=True),
    sa.Column('max_notifications_per_24h', sa.Integer(), nullable=True),
    sa.Column('manual_approval_threshold', sa.Float(), nullable=True),
    sa.Column('max_discount_percentage', sa.Float(), nullable=True),
    sa.Column('degradation_pause_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_policies_id'), 'merchant_policies', ['id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_id'), 'webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_webhook_events_razorpay_event_id'), 'webhook_events', ['razorpay_event_id'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('billing_interval', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('failed_renewal_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_external_subscription_id'), 'subscriptions', ['external_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    op.create_table('payment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('gateway', sa.String(length=100), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_attempts_id'), 'payment_attempts', ['id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('amount_at_risk', sa.Float(), nullable=False),
    sa.Column('recoverable_amount_estimate', sa.Float(), nullable=True),
    sa.Column('recovery_probability', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('attribution_window', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_cases_id'), 'recovery_cases', ['id'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('selected_action', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_id'), 'agent_decisions', ['id'], unique=False)
    op.create_table('experiment_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_assignments_id'), 'experiment_assignments', ['id'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_id'), 'model_predictions', ['id'], unique=False)
    op.create_table('notification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('delivery_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_id'), 'notification_events', ['id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('intervention', sa.String(length=50), nullable=False),
    sa.Column('payment_success', sa.Boolean(), nullable=True),
    sa.Column('gross_recovered', sa.Float(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=True),
    sa.Column('net_recovered', sa.Float(), nullable=True),
    sa.Column('attribution_status', sa.String(length=50), nullable=True),
    sa.Column('recovery_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_index(op.f('ix_outcomes_id'), 'outcomes', ['id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_id'), 'policy_decisions', ['id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recovery_case_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('expected_recovery', sa.Float(), nullable=True),
    sa.Column('expected_cost', sa.Float(), nullable=True),
    sa.Column('expected_net_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_actions_id'), 'recovery_actions', ['id'], unique=False)
    op.create_index(op.f('ix_recovery_actions_idempotency_key'), 'recovery_actions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_actions_idempotency_key'), table_name='recovery_actions')
    op.drop_index(op.f('ix_recovery_actions_id'), table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index(op.f('ix_policy_decisions_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_outcomes_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_notification_events_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_model_predictions_id'), table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index(op.f('ix_experiment_assignments_id'), table_name='experiment_assignments')
    op.drop_table('experiment_assignments')
    op.drop_index(op.f('ix_agent_decisions_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index(op.f('ix_recovery_cases_id'), table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_payment_attempts_id'), table_name='payment_attempts')
    op.drop_table('payment_attempts')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_external_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_webhook_events_razorpay_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_merchant_policies_id'), table_name='merchant_policies')
    op.drop_table('merchant_policies')
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_case_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
