"""
Structured JSON Pydantic Schemas for Multi-LLM Output Validation.
Used across Gemini, OpenAI, and Mock providers for type-safe copy & diagnostic generation.
"""

from typing import Optional, Dict, Any, Literal
from pydantic import BaseModel, Field


ChannelType = Literal["SMS", "WHATSAPP", "EMAIL"]


class CommunicationCopySchema(BaseModel):
    """
    Schema for customer-facing communication copy generated by an LLM provider.
    """
    channel: str = Field(..., description="Communication channel: SMS, WHATSAPP, or EMAIL")
    headline: str = Field(..., description="Short engaging subject line or message headline")
    body: str = Field(..., description="Main message text for the customer")
    cta_text: str = Field(..., description="Call-to-action button or link label text")
    raw_response: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Raw provider metadata")


class DiagnosticSummarySchema(BaseModel):
    """
    Schema for merchant-facing diagnostic reports generated by an LLM provider.
    """
    root_cause_analysis: str = Field(..., description="Technical & behavioural explanation of the payment failure")
    recommended_next_steps: str = Field(..., description="Actionable recommendations for the merchant")
    confidence_explanation: str = Field(..., description="Justification for confidence level and model prediction")
    merchant_notes: str = Field(..., description="Summary notes for dashboard display")
    raw_response: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Raw provider metadata")
